### ISSUE TITLE
Android versions supported?

### ISSUE THREAD

**Issue by emmatyping** [YeomansIII/notiforward-android#3]
It seems based on `Android 6.0 (API Level 23) SDK` in the readme only Android 6.0 is supported. Do you a particular reason? Could 5.1.1 be supported? Thanks for your work!

**Comment by YeomansIII** [comment]
Hello, the current supported versions are 5.0+, the application is simply built against the 6.0 SDK but is compatible with Lollipop and Marshmallow.  I would like to open it up to Kit Kat users as well but there are a few things that I am currently doing that are unsupported and need to find workarounds.

But if you are running 5.1.1, you will be able to run the app perfectly fine on your device.
